This is the script(s) used to make a figure for Kelly Higgins for one of her
sweetness vs bodyweight systematic reviews. The goal is to show systematic 
review conclusions and numbers of random control trials on the same page.


Step one is to read in the data.
```{r}
othr_studies <- read.table("individualStudies.tsv", sep="\t", 
                      encoding = "latin1", header = T)
sr_conclus <- read.table("srStudies.txt", sep="\t", fill=T, header = T)

print(colnames(sr_conclus))

```
create the tables how we need them
Using ggplot2, so need long form of data
Need to select specific columns
```{r}
library(tidyr)
#Reshape SR data
required_columns <- c(4, 14, 17, 19, 20, 23, 25, 26, 29, 31)
my_data <- sr_conclus[,required_columns]
my_data <- tidyr::pivot_longer(data=my_data, cols=2:10, names_to = "result", values_to = "count")
my_data <- aggregate(count ~ result + Year, data=my_data, FUN=sum, drop=F)
my_data$Study.Design <- "Systematic Review"
my_data$Study.level <- "Review"
# make column for colors
my_data$color <- lapply(my_data$result, function(x){
  y = substr(x, 1,3)
  if (y == "BEN") x = "green"
  if (y == "NEU") x = "yellow"
  if (y == "ADV") x = "red"
  return(x)
  })
my_data$conclusion <- lapply(my_data$result, function(x){
  y = substr(x, 1,3)
  if (y == "BEN") x = "Beneficial"
  if (y == "NEU") x = "Neutral"
  if (y == "ADV") x = "Adverse"
  return(x)
  })
my_data$type <- lapply(my_data$result, function(x){
  n <- nchar(x)
  m <- n-2
  y <- substr(x, m,n)
  if (y == "OTH") x = "Both"
  if (y == "INT") x = "Intervention"
  if (y == "OBS") x = "Observational"
  return(x)
  })

my_data$cumsum <- ave(my_data$count, my_data$result, FUN=cumsum)#cumulative sum
for (g in unique(my_data$result)){
  my_years <- my_data$Year[my_data$result == g]
  for (i in min(my_years):max(my_years)){
    one_less <- i-1
    if (one_less %in% my_years & !i %in% my_years){
      new_row <- my_data[my_data$Year == one_less & my_data$result == g,]
      new_row$Year = i
      my_data <- rbind(my_data, new_row)
      my_years <- my_data$Year[my_data$result == g]
    }
    # print(exists(my_data[my_data$Year == i & my_data$result == g]))
  }
}
```


```{r}
#Clean other studies data
othr_studies <- othr_studies[,c("Year", "Study.Design")]
othr_studies$count <- 1
othr_studies$Study.level <- "Primary"
```



```{r}
ggplot2::ggplot() + 
  ggplot2::geom_bar(data = othr_studies, aes(x = Year, y = count, fill = Study.Design),
    stat = "identity", position="stack") +
  scale_y_continuous(sec.axis = sec_axis(~./12.5, name = "Primary Sources"))


```


```{r}
ggplot2::ggplot() + 
  ggplot2::geom_col(data = my_data, aes(x = Year, y = count, fill = result),
    position = "stack", width = 1) +
  ggplot2::geom_col(data = othr_studies, aes(x = Year, y = count, fill = Study.Design),
    position="dodge") +
  scale_fill_manual(values = c("red", "green", "blue", rep("purple",9)))


```




```{r}
#plotting just SR data
# library("ggplot2")
# my_data <- rbind(othr_studies, my_data)
ggplot2::ggplot() + 
  ggplot2::geom_bar(data=my_data, aes(x = Year, y = cumsum, 
                                      fill = as.character(conclusion)),
                    stat = "identity", position = "stack") +
  scale_fill_manual(name = "Conclusion", #setting colors manually
                       values = c("Beneficial" = "green",
                                    "Neutral" = "yellow",
                                    "Adverse" = "red")) +
  scale_x_continuous("Years", breaks = min(my_data$Year):max(my_data$Year),
    labels=min(my_data$Year):max(my_data$Year)) +
  scale_y_continuous("Counts", breaks = min(my_data$cumsum):sum(my_data$cumsum)+1) +
  ggplot2::theme_minimal()


```

```{r}
#plotting just SR data
# install.packages("ggpattern")
library("ggpattern")
ggplot2::ggplot(data=my_data, aes(x = Year, y = cumsum, group=Study.level)) +
  ggpattern::geom_col_pattern(position = "stack",
              aes(pattern = as.character(type),
                  pattern_angle =  as.character(type),
                  fill = as.character(conclusion)),
              pattern_fill = "white",
              pattern_spacing = 0.01,
              width = 0.5) +
  # scale_x_continuous("Years", breaks = min(my_data$Year):max(my_data$Year),
  #   labels=min(my_data$Year):max(my_data$Year)) +
  scale_y_continuous("Counts", breaks = min(my_data$cumsum):sum(my_data$cumsum)+1) +
  ggplot2::theme_minimal() +
  scale_pattern_manual(name="Type",
    values = c("Both" = "stripe",
              "Observational" = "stripe",
              "Intervention" = "none")) +
  scale_pattern_angle_discrete(
    name = "Type",
    # values = c("Both" = 90,
    #           "Observational" = 0,
    #           "Intervention" = 0)
    c(0, 45, 90)
    ) +
  # scale_fill_manual(name = "Conclusion", #setting colors manually
  #                      values = c("Beneficial" = "green",
  #                                 "Neutral" = "yellow",
  #                                 "Adverse" = "red")) +
  ggplot2::geom_col(data = othr_studies, aes(x = Year, y = count, fill = Study.Design),
    position="stack", width = 0.5) +
  scale_fill_manual(name = "Study Types", #setting colors manually
                       values = c("RCT" = "orange",
                                  "Cross-sectional" = "purple",
                                  "Cohort"  = "blue",
                                  "Beneficial" = "green",
                                  "Neutral" = "yellow",
                                  "Adverse" = "red")) 
  # scale_y_continuous(sec.axis = sec_axis(~./12.5, name = "Primary Sources"))
# guides(fill = guide_legend(override.aes =
#                              list(
#                                pattern = c("none", "crosshatch", "stripe"),
#                                pattern_spacing = .01,
#                                pattern_angle = c(0, 0, 45)
#                                )
#                            ))


```


```{r}
#close to working
library("ggpattern")
ggplot2::ggplot(data=my_data, aes(x = Year, y = cumsum, group=result)) +
  ggpattern::geom_col_pattern(position = "stack",
              aes(pattern = as.character(type), fill = as.character(conclusion))
           )
```











